steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
   - name: python
  entrypoint: python
  args: ["unittestcases.py","--junitxml=${SHORT_SHA}_test_log.xml"] 
