steps:
  # Install dependencies
  - name: python
    id: dependencies
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  # automated unit test cases
  - name: python
    id: unittesting
    entrypoint: python
    args: ["unittestcases.py"]
  #generating the egg/distribution file 
  - name: python
    id: build
    entrypoint: python
    args: ["setup.py","sdist"]
  # build push
#   - name: python
#     id: push egg
#     entrypoint: python
#     args: ["buildpush.py"]
  #deleting the current version
  - name: google/cloud-sdk
    id: delete version
    args: ['gcloud', 'artifacts','versions','delete','0.1','--package=codefile','--repository=demo-repo','--location=asia-south1']
  #push to repository
  - name: python
    id: build push
    entrypoint: python
    args: ["-m","twine","upload","--repository-url", "https://asia-south1-python.pkg.dev/mytest-316909/demo-repo/", "dist/*", "--verbose"]
    
#gcloud artifacts versions delete VERSION \
#     --package=PACKAGE \
#     [--repository=REPOSITORY] [--location=LOCATION]      
  
    
